application: youtube-dl

version: alpha-3-2
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /api/.*
  script: mainGAE.py

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  static_files: index.html
  upload: index.html

libraries:
- name: webapp2
  version: "2.5.1"
